CREATE TABLE goodsCategory (
  `id` INT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
  `categoryName` VARCHAR(50) COMMENT '分类名称',
  `createTime` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updateTime` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '修改时间',
  `isDeleted` TINYINT DEFAULT 0 COMMENT '逻辑删除属性，0表示未删除，1表示已删除'
) COMMENT '货物分类表';
